### ISSUE TITLE
Plugin does not work in 4.9.0 

### ISSUE THREAD

**Issue by snyrkill** [rundeck-plugins/ui-job-graph#6]
The plugin works fine in Rundeck 4.8.0 but does not load in 4.9.0 snapshot.

**Comment by akh13** [comment]
I've been experimenting on a few installations, and submitted #8 to address what I think this might be. It worked just fine until an update to 4.9.0, then it broke. These changes got it working again, but I would definitely appreciate a second set of eyes if someone wishes to confirm.

**Comment by akh13** [comment]
Plugin confirmed to work with 4.11.0 with the above, but with a lot of jobs, it does take some time to display the graph (~5s).

**Comment by snyrkill** [comment]
This works now, thank you.
